language: r
sudo: false
cache: packages
pandoc: false

r:
  - 3.1
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - ghostscript

notifications:
  email:
    on_success: change
    on_failure: change
